BUCKET_NAME="charlie"
AWS_NODES=["10.142.170.101", "10.142.170.102"]
AZURE_NODES=[""]
AWS=True
USERNAME="charlie"
PASSWORD="password"
ADMIN_USER="Administrator"
ADMIN_PASS="password"
DDOC_NAME="orders"
VIEW_NAME="by_timestamp"